"$schema" = "https://starship.rs/config-schema.json"

# Only show directory + prompt symbol
format = """
$directory
$character
"""

# ---------------- DIRECTORY ----------------
[directory]
style = "fg:#d8dee9"
format = "$path"
truncation_length = 3
truncation_symbol = "…/"

# ---------------- PROMPT CHARACTER ----------------
[character]
success_symbol = "[❯](fg:#81a1c1)"
error_symbol   = "[❯](fg:#bf616a)"
