force_keyboard_focus = true                                                 # forces keyboard forcus to stay in Walker
theme = "everforest"                                                            # the theme to use, must be in themes/ folder
selection_wrap = true                                                       # wrap list if at bottom or top
hide_action_hints = true                                                    # globally hide the action hints

[placeholders]
"default" = { input = "ÔÄÇ Search...", list = "No Results" } # placeholders for input and empty list, key is the providers name, so f.e. "desktopapplications" or "menus:other"

[keybinds]
quick_activate = []

[columns]
symbols = 1 # providers to be queried by default

[providers]
max_results = 256 # 256 should be enough for everyone
default = [
  "desktopapplications",
  "websearch",
  "scripts",
]

[[providers.prefixes]]
prefix = "/"
provider = "providerlist"

[[providers.prefixes]]
prefix = "."
provider = "files"

[[providers.prefixes]]
prefix = ":"
provider = "symbols"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "@"
provider = "websearch"

[[providers.prefixes]]
prefix = "$"
provider = "clipboard"

[[emergencies]]
text = "Restart Walker"
command = "omarchy-restart-walker"

[[providers.prefixes]]
prefix = "!"
provider = "scripts"

[[scripts]]
name = "Wallpapers"
path = "~/arch/bin/wallpaper-picker"
icon = "üñºÔ∏è"
